// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 11.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Sitecore.T4Class.Generate.Module.PresentationLayer.T4Template
{
    using System.Linq;
    using System.Text;
    using System.Globalization;
    using System.Collections.Generic;
    using Sitecore.Data;
    using Sitecore.Data.Items;
    using Sitecore.Data.Fields;
    using Sitecore.T4Class.Generate.Module.BusinessLayer.Extentions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "M:\localhost\Sitecore\scT4Template\Website\sitecore modules\Sitecore.T4Class.Generate.Module\PresentationLayer\T4Template\T4TemplateClass.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class T4TemplateClass : T4TemplateClassBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(" \r\n");
            this.Write(" \r\n");
            this.Write(" \r\n");
            this.Write(" \r\n");
            this.Write(" \r\n");
            this.Write("namespace ");
            
            #line 19 "M:\localhost\Sitecore\scT4Template\Website\sitecore modules\Sitecore.T4Class.Generate.Module\PresentationLayer\T4Template\T4TemplateClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(namespaceName));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 21 "M:\localhost\Sitecore\scT4Template\Website\sitecore modules\Sitecore.T4Class.Generate.Module\PresentationLayer\T4Template\T4TemplateClass.tt"
foreach (string oneUsing in usingNamespaces.Split(';')){
            
            #line default
            #line hidden
            
            #line 22 "M:\localhost\Sitecore\scT4Template\Website\sitecore modules\Sitecore.T4Class.Generate.Module\PresentationLayer\T4Template\T4TemplateClass.tt"
 if(!string.IsNullOrEmpty(oneUsing)) {
            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 23 "M:\localhost\Sitecore\scT4Template\Website\sitecore modules\Sitecore.T4Class.Generate.Module\PresentationLayer\T4Template\T4TemplateClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(oneUsing.Trim()));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 24 "M:\localhost\Sitecore\scT4Template\Website\sitecore modules\Sitecore.T4Class.Generate.Module\PresentationLayer\T4Template\T4TemplateClass.tt"
}
            
            #line default
            #line hidden
            
            #line 25 "M:\localhost\Sitecore\scT4Template\Website\sitecore modules\Sitecore.T4Class.Generate.Module\PresentationLayer\T4Template\T4TemplateClass.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 27 "M:\localhost\Sitecore\scT4Template\Website\sitecore modules\Sitecore.T4Class.Generate.Module\PresentationLayer\T4Template\T4TemplateClass.tt"
 if(classType.Contains("Glass")) {
            
            #line default
            #line hidden
            this.Write("\t[SitecoreType]\r\n");
            
            #line 29 "M:\localhost\Sitecore\scT4Template\Website\sitecore modules\Sitecore.T4Class.Generate.Module\PresentationLayer\T4Template\T4TemplateClass.tt"
}
            
            #line default
            #line hidden
            this.Write("\tpublic class ");
            
            #line 30 "M:\localhost\Sitecore\scT4Template\Website\sitecore modules\Sitecore.T4Class.Generate.Module\PresentationLayer\T4Template\T4TemplateClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("\r\n\t{ \r\n");
            
            #line 32 "M:\localhost\Sitecore\scT4Template\Website\sitecore modules\Sitecore.T4Class.Generate.Module\PresentationLayer\T4Template\T4TemplateClass.tt"
foreach (Sitecore.Data.Items.TemplateFieldItem field in classFields){
            
            #line default
            #line hidden
            
            #line 33 "M:\localhost\Sitecore\scT4Template\Website\sitecore modules\Sitecore.T4Class.Generate.Module\PresentationLayer\T4Template\T4TemplateClass.tt"
 if(classType.Contains("Glass")) {
            
            #line default
            #line hidden
            this.Write("\t\t[SitecoreField]\r\n");
            
            #line 35 "M:\localhost\Sitecore\scT4Template\Website\sitecore modules\Sitecore.T4Class.Generate.Module\PresentationLayer\T4Template\T4TemplateClass.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\tpublic ");
            
            #line 36 "M:\localhost\Sitecore\scT4Template\Website\sitecore modules\Sitecore.T4Class.Generate.Module\PresentationLayer\T4Template\T4TemplateClass.tt"
 if(classType.Contains("Glass")) {
            
            #line default
            #line hidden
            this.Write("virtual ");
            
            #line 36 "M:\localhost\Sitecore\scT4Template\Website\sitecore modules\Sitecore.T4Class.Generate.Module\PresentationLayer\T4Template\T4TemplateClass.tt"
}
            
            #line default
            #line hidden
            
            #line 36 "M:\localhost\Sitecore\scT4Template\Website\sitecore modules\Sitecore.T4Class.Generate.Module\PresentationLayer\T4Template\T4TemplateClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.GetFieldType().Name.TypeFormat()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 36 "M:\localhost\Sitecore\scT4Template\Website\sitecore modules\Sitecore.T4Class.Generate.Module\PresentationLayer\T4Template\T4TemplateClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.FieldNameFormat()));
            
            #line default
            #line hidden
            this.Write("{ get; set; }\r\n\r\n");
            
            #line 38 "M:\localhost\Sitecore\scT4Template\Website\sitecore modules\Sitecore.T4Class.Generate.Module\PresentationLayer\T4Template\T4TemplateClass.tt"
}
            
            #line default
            #line hidden
            this.Write("\t}\r\n}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "M:\localhost\Sitecore\scT4Template\Website\sitecore modules\Sitecore.T4Class.Generate.Module\PresentationLayer\T4Template\T4TemplateClass.tt"

private global::System.Collections.Generic.List<Sitecore.Data.Items.TemplateFieldItem> _classFieldsField;

/// <summary>
/// Access the classFields parameter of the template.
/// </summary>
private global::System.Collections.Generic.List<Sitecore.Data.Items.TemplateFieldItem> classFields
{
    get
    {
        return this._classFieldsField;
    }
}

private string _namespaceNameField;

/// <summary>
/// Access the namespaceName parameter of the template.
/// </summary>
private string namespaceName
{
    get
    {
        return this._namespaceNameField;
    }
}

private string _usingNamespacesField;

/// <summary>
/// Access the usingNamespaces parameter of the template.
/// </summary>
private string usingNamespaces
{
    get
    {
        return this._usingNamespacesField;
    }
}

private string _classNameField;

/// <summary>
/// Access the className parameter of the template.
/// </summary>
private string className
{
    get
    {
        return this._classNameField;
    }
}

private string _classTypeField;

/// <summary>
/// Access the classType parameter of the template.
/// </summary>
private string classType
{
    get
    {
        return this._classTypeField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool classFieldsValueAcquired = false;
if (this.Session.ContainsKey("classFields"))
{
    if ((typeof(global::System.Collections.Generic.List<Sitecore.Data.Items.TemplateFieldItem>).IsAssignableFrom(this.Session["classFields"].GetType()) == false))
    {
        this.Error("The type \'System.Collections.Generic.List<Sitecore.Data.Items.TemplateFieldItem>\'" +
                " of the parameter \'classFields\' did not match the type of the data passed to the" +
                " template.");
    }
    else
    {
        this._classFieldsField = ((global::System.Collections.Generic.List<Sitecore.Data.Items.TemplateFieldItem>)(this.Session["classFields"]));
        classFieldsValueAcquired = true;
    }
}
if ((classFieldsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("classFields");
    if ((data != null))
    {
        if ((typeof(global::System.Collections.Generic.List<Sitecore.Data.Items.TemplateFieldItem>).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'System.Collections.Generic.List<Sitecore.Data.Items.TemplateFieldItem>\'" +
                    " of the parameter \'classFields\' did not match the type of the data passed to the" +
                    " template.");
        }
        else
        {
            this._classFieldsField = ((global::System.Collections.Generic.List<Sitecore.Data.Items.TemplateFieldItem>)(data));
        }
    }
}
bool namespaceNameValueAcquired = false;
if (this.Session.ContainsKey("namespaceName"))
{
    if ((typeof(string).IsAssignableFrom(this.Session["namespaceName"].GetType()) == false))
    {
        this.Error("The type \'System.String\' of the parameter \'namespaceName\' did not match the type " +
                "of the data passed to the template.");
    }
    else
    {
        this._namespaceNameField = ((string)(this.Session["namespaceName"]));
        namespaceNameValueAcquired = true;
    }
}
if ((namespaceNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("namespaceName");
    if ((data != null))
    {
        if ((typeof(string).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'System.String\' of the parameter \'namespaceName\' did not match the type " +
                    "of the data passed to the template.");
        }
        else
        {
            this._namespaceNameField = ((string)(data));
        }
    }
}
bool usingNamespacesValueAcquired = false;
if (this.Session.ContainsKey("usingNamespaces"))
{
    if ((typeof(string).IsAssignableFrom(this.Session["usingNamespaces"].GetType()) == false))
    {
        this.Error("The type \'System.String\' of the parameter \'usingNamespaces\' did not match the typ" +
                "e of the data passed to the template.");
    }
    else
    {
        this._usingNamespacesField = ((string)(this.Session["usingNamespaces"]));
        usingNamespacesValueAcquired = true;
    }
}
if ((usingNamespacesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("usingNamespaces");
    if ((data != null))
    {
        if ((typeof(string).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'System.String\' of the parameter \'usingNamespaces\' did not match the typ" +
                    "e of the data passed to the template.");
        }
        else
        {
            this._usingNamespacesField = ((string)(data));
        }
    }
}
bool classNameValueAcquired = false;
if (this.Session.ContainsKey("className"))
{
    if ((typeof(string).IsAssignableFrom(this.Session["className"].GetType()) == false))
    {
        this.Error("The type \'System.String\' of the parameter \'className\' did not match the type of t" +
                "he data passed to the template.");
    }
    else
    {
        this._classNameField = ((string)(this.Session["className"]));
        classNameValueAcquired = true;
    }
}
if ((classNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("className");
    if ((data != null))
    {
        if ((typeof(string).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'System.String\' of the parameter \'className\' did not match the type of t" +
                    "he data passed to the template.");
        }
        else
        {
            this._classNameField = ((string)(data));
        }
    }
}
bool classTypeValueAcquired = false;
if (this.Session.ContainsKey("classType"))
{
    if ((typeof(string).IsAssignableFrom(this.Session["classType"].GetType()) == false))
    {
        this.Error("The type \'System.String\' of the parameter \'classType\' did not match the type of t" +
                "he data passed to the template.");
    }
    else
    {
        this._classTypeField = ((string)(this.Session["classType"]));
        classTypeValueAcquired = true;
    }
}
if ((classTypeValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("classType");
    if ((data != null))
    {
        if ((typeof(string).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'System.String\' of the parameter \'classType\' did not match the type of t" +
                    "he data passed to the template.");
        }
        else
        {
            this._classTypeField = ((string)(data));
        }
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public class T4TemplateClassBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
